# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Email Report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  email_report:
    runs-on: ubuntu-latest
    steps:
      - name: Email report
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Report"
          body: "Please find attached the daily report."
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: deploy-report.txt

      - name: Delete the report
        run: rm deploy-report.txt